### ISSUE TITLE
Adding LinkedIn in Resume Header 

### ISSUE THREAD

**Issue by Alymostafa** [thehale/expressive-resume#1]
Can you give an explanation of adding LinkedIn command in the resume header?

**Comment by thehale** [comment]
Yep!

There isn't yet a `\linkedin` command, but the appropriate place to create that would be in the [Expressive.cls (line 110)](https://github.com/jhale1805/expressive-resume/blob/main/src/Expressive.cls#L110) file that the resume/cover letter classes inherit from. You can design that command after style used for github, email, etc.

Once you've created the `\linkedin` command, you can add it to the `\resumeheader` by creating a new option for it in [ExpressiveResume.cls (line 19)](https://github.com/jhale1805/expressive-resume/blob/main/src/ExpressiveResume.cls#L19).

For consistency, it would also be good to add that option to the `\coverletterheader` too which can be found in [ExpressiveCoverLetter.cls (line 23)](https://github.com/jhale1805/expressive-resume/blob/main/src/ExpressiveCoverLetter.cls#L23).
