### ISSUE TITLE
Subitems in work experience section

### ISSUE THREAD

**Issue by dshang1534** [thehale/expressive-resume#2]
The expressive resume is expressive!

I'm wondering if I can add subitems under main items in the work experience section. It's a personal preference for organizing the resume. It's just nice to have.

Something like this:
<img width="283" alt="Screen Shot 2022-02-08 at 1 01 13 PM" src="https://user-images.githubusercontent.com/78217710/153047984-e0ac0cbb-d236-4aa7-a271-29a1af62cfaa.png">

**Comment by thehale** [comment]
Great question! This is already possible with the current version of `expressive-resume`.

**Examples**:
```LaTeX
\section{Work Experience}

\experience{Summer Intern}{Radiant Software Systems}{Aug 2021}{May 2021}{
    \achievement{
        Developed a mobile app in \tech{React Native} that was
        downloaded 100k times on Google Play.
        
        % You can nest achievements
        \achievement{ Sub-achievement 1 }
        \achievement{ Sub-achievement 2 }
        
        % If you want a numbered sub-list, use the `enumerate` environment.
        \begin{enumerate}
            \item Sub-point 1
            \item Sub-point 2
        \end{enumerate}
    }
}
```
![image](https://user-images.githubusercontent.com/47901316/153085806-544a2ac2-7eec-4b36-a67d-4850fdf8ca9b.png)

**How it works**
[Under the hood](https://github.com/jhale1805/expressive-resume/blob/e4db0a37af61adc8b4b5049c3370453e71a5e6a4/src/Expressive.cls#L116), the `\achievement{ TEXT }` command is just a wrapper for the `itemize` environment built into LaTeX with some added formatting. All the `TEXT` you enter is considered part of one `\item` of that environment. As a result, any LaTeX code you can put inside of an `\item` can be passed as the `TEXT` of the `\achievement`.

**Contribution Recommendation**
If you're feeling ambitious, feel free to open a PR creating a new `docs` folder with a set of more advanced/detailed documentation to include use cases like this one that are outside of the scope of the **Quickstart** in the `README.md`.
