### ISSUE TITLE
Rename `Company` parameter to `Organization` in the `\experience` command

### ISSUE THREAD

**Issue by thehale** [thehale/expressive-resume#3]
Welcome to GitHub! This issue is reserved for people who have never contributed to an open-source project before. If that sounds like you, feel free to comment below to claim this issue as your own and I'll help walk you through the process of completing your very first contribution!

**The Problem**
[This line](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L67) of the `README.md` describes the parameters for the `\experience` command. Currently it names the second parameter `Company`, but a name like `Organization` would better include experience as a volunteer or working for a government organization. 

**The Solution**
1. Click the **Fork** button to make your own copy of this repository.
2. Open the `README.md` and click the pencil icon to edit it.
3. Find the line linked above and change the word `Company` to `Organization`.
4. **Commit** your change.
   - For the commit title, put the title of this issue.
   - For the description, go ahead and share your thoughts about making your first open-source contribution!
   - End the description with `Closes jhale1805/expressive-resume#3` to link your commit to this issue.
5. Open a **Pull Request**

From there, I will get a notification, at which point I will quickly double-check your changes and incorporate them into `expressive-resume`!

If you have questions about any of these steps or are feeling stuck, just comment your concern below and I'll jump in to give more detailed guidance. :D

**Comment by ChrisCoastal** [comment]
Hi jhale, could I please claim this issue? I'm still learning github and this seems like a nice simple issue for me to tackle. Thanks also for creating a first timers issue!

**Comment by thehale** [comment]
Hi @ChrisCoastal ! It looks like @iku12phycho beat you to this one, but I'll try to make another similar issue that you can take ownership of.

You are also welcome to take a look through the `README.md` file yourself and use the steps I outlined in this issue to improve some other piece of the documentation for `expressive-resume`. The only difference will be that step 3 will modify a different part of the README.

Thanks so much for your interest. So sorry that this particular one got picked up so quickly!

**Comment by ChrisCoastal** [comment]
Thanks for the reply. I should have looked more carefully before commenting.

I'll take a look at the file and see if there is anything I could recommend. Appreciate the offer.

**Comment by thehale** [comment]
>Thanks for the reply. I should have looked more carefully before commenting.

No worries at all @ChrisCoastal! I was super surprised at how quickly you two jumped on this issue!

>I'll take a look at the file and see if there is anything I could recommend. Appreciate the offer.

Sounds great! Also feel free to check out issue #4 which I created with you in mind (I tried to tag you in it so you may have already seen it). I'll give you dibs on that one for the next 2-3 days, after which I'll open it up to anyone else who comments interest in participating in it.
