### ISSUE TITLE
Improve command descriptions in the **Quickstart**

### ISSUE THREAD

**Issue by thehale** [thehale/expressive-resume#4]
Welcome to GitHub! This issue is reserved for people who have never contributed to an open-source project before. If that sounds like you, feel free to comment below to claim this issue as your own and I'll help walk you through the process of completing your very first contribution!

**The Problem**
In the `README.md`, several of the LaTeX code examples use passive voice to explain how they should be used. I think the documentation would be a little more engaging to read if these examples were changed to active voice.

Here are the particular examples.
1. [Starting an Expressive Resume](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L32)
2. [The `\objective` command](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L61)
3. [Starting an Expressive Cover Letter](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L102)

**The Solution**
1. Click the **Fork** button to make your own copy of this repository.
2. Open the `README.md` and click the pencil icon to edit it.
3. Fix the three lines mentioned earlier.
   - For the [first one](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L32), change `% The contents of your resume will go here.` to `% You will write your resume here`
   - For the [second one](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L61), change `% Your objective statement here.` to `% Write your objective statement here.`
   - For the [third one](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L102)
, change `% The contents of your cover letter will go here.` to `% You will write your cover letter here`
4. **Commit** your change.
   - For the commit title, put the title of this issue.
   - For the description, go ahead and share your thoughts about making your first open-source contribution!
   - End the description with `Closes jhale1805/expressive-resume#4` to link your commit to this issue.
5. Open a **Pull Request**, and make sure to direct it to merge into `jhale1805/expressive-resume` with a **base** of `main`.

From there, I will get a notification, at which point I will quickly double-check your changes and incorporate them into `expressive-resume`!

If you have questions about any of these steps or are feeling stuck, just comment your concern below and I'll jump in to give more detailed guidance. :D

**Comment by thehale** [comment]
@ChrisCoastal, you are welcome to have dibs on this issue if you want it!

**Comment by ChrisCoastal** [comment]
@jhale1805 Thanks for thinking of me and creating this issue. I would be happy to make the changes.
