### ISSUE TITLE
How to convert .tex to .pdf ?

### ISSUE THREAD

**Issue by aasthavar** [thehale/expressive-resume#7]

**Comment by thehale** [comment]
Hello @aasthavar !

Make sure to follow the instructions for setting up the project on your computer: https://github.com/thehale/expressive-resume#installation--setup

After opening the project inside of the "Devcontainer", saved edits to your `.tex` file will automatically trigger the build of a `.pdf` of the result.

_If you have further difficulties, feel free to re-open the issue with additional details (e.g. error messages, screenshots, etc.)_
