### ISSUE TITLE
Changing the name of Objective to Summary

### ISSUE THREAD

**Issue by aval-s** [thehale/expressive-resume#9]
Is there a way to change "Objective" heading to "Summary?"

**Comment by thehale** [comment]
I'm guessing you already found the answer for yourself. For anyone else arriving here later, here's the section of code to update:

https://github.com/thehale/expressive-resume/blob/eb39f5a0832ba3424880cd7b5837798c79b3e454/src/ExpressiveResume.cls#L80-L84

On line 82, change `Objective` to `Summary` (or whatever other term you prefer)
